/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import carScene from '../assets/car_scene.glb'

const Car = (props) => {
    const { nodes, materials } = useGLTF(carScene)
    return (
        <group {...props} dispose={null}>
            <group position={[0, -0.507, -0.126]} scale={0.004}>
                <group position={[-158.903, 66.999, -212.943]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.WRR_Material027_0.geometry}
                        material={materials['Material.027']}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.WRR_Material031_0.geometry}
                        material={materials['Material.031']}
                    />
                </group>
                <group position={[158.903, 66.999, -212.943]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.WRL_Material027_0.geometry}
                        material={materials['Material.027']}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.WRL_Material031_0.geometry}
                        material={materials['Material.031']}
                    />
                </group>
                <group position={[158.104, 65.034, 294.549]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.WFL_Material027_0.geometry}
                        material={materials['Material.027']}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.WFL_Material031_0.geometry}
                        material={materials['Material.031']}
                    />
                </group>
                <group position={[-158.104, 65.034, 294.549]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.WFR_Material027_0.geometry}
                        material={materials['Material.027']}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.WFR_Material031_0.geometry}
                        material={materials['Material.031']}
                    />
                </group>
                <group position={[0, 138.332, 1.537]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.CarBody_Material028_0.geometry}
                        material={materials['Material.028']}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.CarBody_Carcamero_ma_0.geometry}
                        material={materials.Carcamero_ma}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.CarBody_Material032_0.geometry}
                        material={materials['Material.032']}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.CarBody_Material029_0.geometry}
                        material={materials['Material.029']}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.CarBody_Material026_0.geometry}
                        material={materials['Material.026']}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.CarBody_Material025_0.geometry}
                        material={materials['Material.025']}
                    />
                </group>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.TailLight_Material030_0.geometry}
                    material={materials['Material.030']}
                    position={[0, 160.718, -377.627]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={100}
                />
            </group>
        </group>
    )
}

export default Car;
